version: 2

models:
  - name: PIX301_inbound_48
    description: This table contains the combined data for PIX301

    columns:
      - name: id
        description: This is a unique identifier for each message

      - name: processed
        description: Whether the message has been processed

      - name: received_date
        description: When was the message received by this channel

      - name: client_id
        description: The name of the client who sent the message

      - name: response_date
        description: Date a response was sent 

      - name: connector
        description: Destination connection

      - name: error_code
        description: Message status

  - name: PIX302_inbound_50
    description: This table contains the combined data for PIX302

    columns:
      - name: id
        description: This is a unique identifier for each message

      - name: processed
        description: Whether the message has been processed

      - name: received_date
        description: When was the message received by this channel

      - name: client_id
        description: The name of the client who sent the message

      - name: response_date
        description: Date a response was sent 

      - name: connector
        description: Destination connection

      - name: error_code
        description: Message status

