version: 2

models:
  - name: PIX301_inbound_48
    description: This table contains the combined data for PIX301

    columns:
      - name: id
        description: This is a unique identifier for each message

      - name: processed
        description: Whether the message has been processed

      - name: received_date
        description: When was the message received by this channel

      - name: client_id
        description: The name of the client who sent the message

      - name: response_date
        description: Date a response was sent 

      - name: connector_name
        description: Destination connection

      - name: error_code
        description: Message status

  - name: PIX302_inbound_50
    description: This table contains the combined data for PIX302

    columns:
      - name: id
        description: This is a unique identifier for each message

      - name: processed
        description: Whether the message has been processed

      - name: received_date
        description: When was the message received by this channel

      - name: client_id
        description: The name of the client who sent the message

      - name: response_date
        description: Date a response was sent 

      - name: connector_name
        description: Destination connection

      - name: error_code
        description: Message status

  - name: PIX309_inbound_49
    description: This table contains the combined data for PIX309

    columns:
      - name: id
        description: This is a unique identifier for each message

      - name: processed
        description: Whether the message has been processed

      - name: received_date
        description: When was the message received by this channel

      - name: client_id
        description: The name of the client who sent the message

      - name: response_date
        description: Date a response was sent 

      - name: connector_name
        description: Destination connection

      - name: error_code
        description: Message status

  - name: PNR_inbound_45
    description: This table contains the combined data for PIX309

    columns:
      - name: id
        description: This is a unique identifier for each message

      - name: processed
        description: Whether the message has been processed

      - name: received_date
        description: When was the message received by this channel

      - name: client_id
        description: The name of the client who sent the message

      - name: response_date
        description: Date a response was sent 

      - name: connector_name
        description: Destination connection

      - name: error_code
        description: Message status

  - name: DQ_inbound_47
    Description: This table contains the combined data for the inbound DQ

    columns:
      - name: id
        description: This is a unique identifier for each message

      - name: processed
        description: Whether the message has been processed

      - name: received_date
        description: When was the message received by this channel

      - name: client_id
        description: The name of the client who sent the message

      - name: response_date
        description: Date a response was sent 

      - name: connector_name
        description: Destination connection

      - name: error_code
        description: Message status

  - name: DR_inbound_43
    Description: This table contains the combined data for the inbound DR

    columns:
      - name: id
        description: This is a unique identifier for each message

      - name: processed
        description: Whether the message has been processed

      - name: received_date
        description: When was the message received by this channel

      - name: client_id
        description: The name of the client who sent the message

      - name: response_date
        description: Date a response was sent 

      - name: connector_name
        description: Destination connection

      - name: error_code
        description: Message status

  - name: PNR_inbound_46
    Description: This table contains the combined data for the inbound PNR

    columns:
      - name: id
        description: This is a unique identifier for each message

      - name: processed
        description: Whether the message has been processed

      - name: received_date
        description: When was the message received by this channel

      - name: client_id
        description: The name of the client who sent the message

      - name: response_date
        description: Date a response was sent 

      - name: connector_name
        description: Destination connection

      - name: error_code
        description: Message status

  - name: Registration_prefetch_75
    Description: This table contains the combined data for the registration prefetch

    columns:
      - name: id
        description: This is a unique identifier for each message

      - name: processed
        description: Whether the message has been processed

      - name: received_date
        description: When was the message received by this channel

      - name: client_id
        description: The name of the client who sent the message

      - name: response_date
        description: Date a response was sent 

      - name: connector_name
        description: Destination connection

      - name: error_code
        description: Message status

  - name: PIX301_Outbound_Velatura
    Description: This table contains the combined data for the PIX301 Outbound to Velatura

    columns:
      - name: id
        description: This is a unique identifier for each message

      - name: processed
        description: Whether the message has been processed

      - name: received_date
        description: When was the message received by this channel

      - name: response_code
        description: The response code from the transaction

      - name: response_status
        description: The response status from the transaction

      - name: response_date
        description: Date a response was sent 

      - name: connector_name
        description: Destination connection

      - name: error_code
        description: Message status        
